### ISSUE TITLE
Can't add my people page

### ISSUE THREAD

**Issue by sedkis** [RESTFest/2019-Greenville#1]
Hello - I do not have permission to add to my page for Greenville

Can you add me please? My name is Sedky Abou-Shamalah

**Comment by oestrich** [comment]
You should have an invite!

**Comment by sedkis** [comment]
It didn't work - I think it is because when I was originally signed up the wrong username was used for GH.  I tried setting it to a new one and I get the new invites but it doesn't work

**Comment by oestrich** [comment]
I cancelled the invite and sent another to your @sedkis user. Hopefully that one went through!

**Comment by sedkis** [comment]
Fixed! Thanks
